
---

## 游꿛 2. Archivo `_config.yml`

Este archivo le dice a **GitHub Pages** c칩mo mostrar tu Markdown como una p치gina web bonita (usa Jekyll autom치ticamente):

```yaml
theme: jekyll-theme-cayman
title: Portafolio: Teor칤a de la Programaci칩n
description: Portafolio acad칠mico en formato Markdown
